// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	domain "flamingo.me/form/domain"
	mock "github.com/stretchr/testify/mock"
)

// FormDataEncoderFactory is an autogenerated mock type for the FormDataEncoderFactory type
type FormDataEncoderFactory struct {
	mock.Mock
}

// CreateByNamedEncoder provides a mock function with given fields: name
func (_m *FormDataEncoderFactory) CreateByNamedEncoder(name string) domain.FormDataEncoder {
	ret := _m.Called(name)

	var r0 domain.FormDataEncoder
	if rf, ok := ret.Get(0).(func(string) domain.FormDataEncoder); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.FormDataEncoder)
		}
	}

	return r0
}

// CreateWithFormService provides a mock function with given fields: formService
func (_m *FormDataEncoderFactory) CreateWithFormService(formService domain.FormService) domain.FormDataEncoder {
	ret := _m.Called(formService)

	var r0 domain.FormDataEncoder
	if rf, ok := ret.Get(0).(func(domain.FormService) domain.FormDataEncoder); ok {
		r0 = rf(formService)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.FormDataEncoder)
		}
	}

	return r0
}
