// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"flamingo.me/form/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewFormDataEncoderFactory creates a new instance of FormDataEncoderFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFormDataEncoderFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *FormDataEncoderFactory {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &FormDataEncoderFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// FormDataEncoderFactory is an autogenerated mock type for the FormDataEncoderFactory type
type FormDataEncoderFactory struct {
	mock.Mock
}

type FormDataEncoderFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *FormDataEncoderFactory) EXPECT() *FormDataEncoderFactory_Expecter {
	return &FormDataEncoderFactory_Expecter{mock: &_m.Mock}
}

// CreateByNamedEncoder provides a mock function for the type FormDataEncoderFactory
func (_mock *FormDataEncoderFactory) CreateByNamedEncoder(name string) domain.FormDataEncoder {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for CreateByNamedEncoder")
	}

	var r0 domain.FormDataEncoder
	if returnFunc, ok := ret.Get(0).(func(string) domain.FormDataEncoder); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.FormDataEncoder)
		}
	}
	return r0
}

// FormDataEncoderFactory_CreateByNamedEncoder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateByNamedEncoder'
type FormDataEncoderFactory_CreateByNamedEncoder_Call struct {
	*mock.Call
}

// CreateByNamedEncoder is a helper method to define mock.On call
//   - name string
func (_e *FormDataEncoderFactory_Expecter) CreateByNamedEncoder(name any) *FormDataEncoderFactory_CreateByNamedEncoder_Call {
	return &FormDataEncoderFactory_CreateByNamedEncoder_Call{Call: _e.mock.On("CreateByNamedEncoder", name)}
}

func (_c *FormDataEncoderFactory_CreateByNamedEncoder_Call) Run(run func(name string)) *FormDataEncoderFactory_CreateByNamedEncoder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *FormDataEncoderFactory_CreateByNamedEncoder_Call) Return(formDataEncoder domain.FormDataEncoder) *FormDataEncoderFactory_CreateByNamedEncoder_Call {
	_c.Call.Return(formDataEncoder)
	return _c
}

func (_c *FormDataEncoderFactory_CreateByNamedEncoder_Call) RunAndReturn(run func(name string) domain.FormDataEncoder) *FormDataEncoderFactory_CreateByNamedEncoder_Call {
	_c.Call.Return(run)
	return _c
}

// CreateWithFormService provides a mock function for the type FormDataEncoderFactory
func (_mock *FormDataEncoderFactory) CreateWithFormService(formService domain.FormService) domain.FormDataEncoder {
	ret := _mock.Called(formService)

	if len(ret) == 0 {
		panic("no return value specified for CreateWithFormService")
	}

	var r0 domain.FormDataEncoder
	if returnFunc, ok := ret.Get(0).(func(domain.FormService) domain.FormDataEncoder); ok {
		r0 = returnFunc(formService)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.FormDataEncoder)
		}
	}
	return r0
}

// FormDataEncoderFactory_CreateWithFormService_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWithFormService'
type FormDataEncoderFactory_CreateWithFormService_Call struct {
	*mock.Call
}

// CreateWithFormService is a helper method to define mock.On call
//   - formService domain.FormService
func (_e *FormDataEncoderFactory_Expecter) CreateWithFormService(formService any) *FormDataEncoderFactory_CreateWithFormService_Call {
	return &FormDataEncoderFactory_CreateWithFormService_Call{Call: _e.mock.On("CreateWithFormService", formService)}
}

func (_c *FormDataEncoderFactory_CreateWithFormService_Call) Run(run func(formService domain.FormService)) *FormDataEncoderFactory_CreateWithFormService_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 domain.FormService
		if args[0] != nil {
			arg0 = args[0].(domain.FormService)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *FormDataEncoderFactory_CreateWithFormService_Call) Return(formDataEncoder domain.FormDataEncoder) *FormDataEncoderFactory_CreateWithFormService_Call {
	_c.Call.Return(formDataEncoder)
	return _c
}

func (_c *FormDataEncoderFactory_CreateWithFormService_Call) RunAndReturn(run func(formService domain.FormService) domain.FormDataEncoder) *FormDataEncoderFactory_CreateWithFormService_Call {
	_c.Call.Return(run)
	return _c
}
