// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "flamingo.me/form/domain"
	mock "github.com/stretchr/testify/mock"

	url "net/url"

	web "flamingo.me/flamingo/v3/framework/web"
)

// CompleteFormService is an autogenerated mock type for the CompleteFormService type
type CompleteFormService struct {
	mock.Mock
}

type CompleteFormService_Expecter struct {
	mock *mock.Mock
}

func (_m *CompleteFormService) EXPECT() *CompleteFormService_Expecter {
	return &CompleteFormService_Expecter{mock: &_m.Mock}
}

// Decode provides a mock function with given fields: ctx, req, values, formData
func (_m *CompleteFormService) Decode(ctx context.Context, req *web.Request, values url.Values, formData interface{}) (interface{}, error) {
	ret := _m.Called(ctx, req, values, formData)

	if len(ret) == 0 {
		panic("no return value specified for Decode")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *web.Request, url.Values, interface{}) (interface{}, error)); ok {
		return rf(ctx, req, values, formData)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *web.Request, url.Values, interface{}) interface{}); ok {
		r0 = rf(ctx, req, values, formData)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *web.Request, url.Values, interface{}) error); ok {
		r1 = rf(ctx, req, values, formData)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CompleteFormService_Decode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decode'
type CompleteFormService_Decode_Call struct {
	*mock.Call
}

// Decode is a helper method to define mock.On call
//   - ctx context.Context
//   - req *web.Request
//   - values url.Values
//   - formData interface{}
func (_e *CompleteFormService_Expecter) Decode(ctx interface{}, req interface{}, values interface{}, formData interface{}) *CompleteFormService_Decode_Call {
	return &CompleteFormService_Decode_Call{Call: _e.mock.On("Decode", ctx, req, values, formData)}
}

func (_c *CompleteFormService_Decode_Call) Run(run func(ctx context.Context, req *web.Request, values url.Values, formData interface{})) *CompleteFormService_Decode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*web.Request), args[2].(url.Values), args[3].(interface{}))
	})
	return _c
}

func (_c *CompleteFormService_Decode_Call) Return(_a0 interface{}, _a1 error) *CompleteFormService_Decode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CompleteFormService_Decode_Call) RunAndReturn(run func(context.Context, *web.Request, url.Values, interface{}) (interface{}, error)) *CompleteFormService_Decode_Call {
	_c.Call.Return(run)
	return _c
}

// GetFormData provides a mock function with given fields: ctx, req
func (_m *CompleteFormService) GetFormData(ctx context.Context, req *web.Request) (interface{}, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetFormData")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *web.Request) (interface{}, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *web.Request) interface{}); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *web.Request) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CompleteFormService_GetFormData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFormData'
type CompleteFormService_GetFormData_Call struct {
	*mock.Call
}

// GetFormData is a helper method to define mock.On call
//   - ctx context.Context
//   - req *web.Request
func (_e *CompleteFormService_Expecter) GetFormData(ctx interface{}, req interface{}) *CompleteFormService_GetFormData_Call {
	return &CompleteFormService_GetFormData_Call{Call: _e.mock.On("GetFormData", ctx, req)}
}

func (_c *CompleteFormService_GetFormData_Call) Run(run func(ctx context.Context, req *web.Request)) *CompleteFormService_GetFormData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*web.Request))
	})
	return _c
}

func (_c *CompleteFormService_GetFormData_Call) Return(_a0 interface{}, _a1 error) *CompleteFormService_GetFormData_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CompleteFormService_GetFormData_Call) RunAndReturn(run func(context.Context, *web.Request) (interface{}, error)) *CompleteFormService_GetFormData_Call {
	_c.Call.Return(run)
	return _c
}

// Validate provides a mock function with given fields: ctx, req, validatorProvider, formData
func (_m *CompleteFormService) Validate(ctx context.Context, req *web.Request, validatorProvider domain.ValidatorProvider, formData interface{}) (*domain.ValidationInfo, error) {
	ret := _m.Called(ctx, req, validatorProvider, formData)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 *domain.ValidationInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *web.Request, domain.ValidatorProvider, interface{}) (*domain.ValidationInfo, error)); ok {
		return rf(ctx, req, validatorProvider, formData)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *web.Request, domain.ValidatorProvider, interface{}) *domain.ValidationInfo); ok {
		r0 = rf(ctx, req, validatorProvider, formData)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ValidationInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *web.Request, domain.ValidatorProvider, interface{}) error); ok {
		r1 = rf(ctx, req, validatorProvider, formData)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CompleteFormService_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type CompleteFormService_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - ctx context.Context
//   - req *web.Request
//   - validatorProvider domain.ValidatorProvider
//   - formData interface{}
func (_e *CompleteFormService_Expecter) Validate(ctx interface{}, req interface{}, validatorProvider interface{}, formData interface{}) *CompleteFormService_Validate_Call {
	return &CompleteFormService_Validate_Call{Call: _e.mock.On("Validate", ctx, req, validatorProvider, formData)}
}

func (_c *CompleteFormService_Validate_Call) Run(run func(ctx context.Context, req *web.Request, validatorProvider domain.ValidatorProvider, formData interface{})) *CompleteFormService_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*web.Request), args[2].(domain.ValidatorProvider), args[3].(interface{}))
	})
	return _c
}

func (_c *CompleteFormService_Validate_Call) Return(_a0 *domain.ValidationInfo, _a1 error) *CompleteFormService_Validate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CompleteFormService_Validate_Call) RunAndReturn(run func(context.Context, *web.Request, domain.ValidatorProvider, interface{}) (*domain.ValidationInfo, error)) *CompleteFormService_Validate_Call {
	_c.Call.Return(run)
	return _c
}

// NewCompleteFormService creates a new instance of CompleteFormService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCompleteFormService(t interface {
	mock.TestingT
	Cleanup(func())
}) *CompleteFormService {
	mock := &CompleteFormService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
