// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"net/url"

	"flamingo.me/flamingo/v3/framework/web"
	"flamingo.me/form/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewCompleteFormService creates a new instance of CompleteFormService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCompleteFormService(t interface {
	mock.TestingT
	Cleanup(func())
}) *CompleteFormService {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &CompleteFormService{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// CompleteFormService is an autogenerated mock type for the CompleteFormService type
type CompleteFormService struct {
	mock.Mock
}

type CompleteFormService_Expecter struct {
	mock *mock.Mock
}

func (_m *CompleteFormService) EXPECT() *CompleteFormService_Expecter {
	return &CompleteFormService_Expecter{mock: &_m.Mock}
}

// Decode provides a mock function for the type CompleteFormService
func (_mock *CompleteFormService) Decode(ctx context.Context, req *web.Request, values url.Values, formData interface{}) (interface{}, error) {
	ret := _mock.Called(ctx, req, values, formData)

	if len(ret) == 0 {
		panic("no return value specified for Decode")
	}

	var r0 interface{}
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *web.Request, url.Values, interface{}) (interface{}, error)); ok {
		return returnFunc(ctx, req, values, formData)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *web.Request, url.Values, interface{}) interface{}); ok {
		r0 = returnFunc(ctx, req, values, formData)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *web.Request, url.Values, interface{}) error); ok {
		r1 = returnFunc(ctx, req, values, formData)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CompleteFormService_Decode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decode'
type CompleteFormService_Decode_Call struct {
	*mock.Call
}

// Decode is a helper method to define mock.On call
//   - ctx context.Context
//   - req *web.Request
//   - values url.Values
//   - formData interface{}
func (_e *CompleteFormService_Expecter) Decode(ctx any, req any, values any, formData any) *CompleteFormService_Decode_Call {
	return &CompleteFormService_Decode_Call{Call: _e.mock.On("Decode", ctx, req, values, formData)}
}

func (_c *CompleteFormService_Decode_Call) Run(run func(ctx context.Context, req *web.Request, values url.Values, formData interface{})) *CompleteFormService_Decode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *web.Request
		if args[1] != nil {
			arg1 = args[1].(*web.Request)
		}
		var arg2 url.Values
		if args[2] != nil {
			arg2 = args[2].(url.Values)
		}
		var arg3 interface{}
		if args[3] != nil {
			arg3 = args[3].(interface{})
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *CompleteFormService_Decode_Call) Return(ifaceVal interface{}, err error) *CompleteFormService_Decode_Call {
	_c.Call.Return(ifaceVal, err)
	return _c
}

func (_c *CompleteFormService_Decode_Call) RunAndReturn(run func(ctx context.Context, req *web.Request, values url.Values, formData interface{}) (interface{}, error)) *CompleteFormService_Decode_Call {
	_c.Call.Return(run)
	return _c
}

// GetFormData provides a mock function for the type CompleteFormService
func (_mock *CompleteFormService) GetFormData(ctx context.Context, req *web.Request) (interface{}, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetFormData")
	}

	var r0 interface{}
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *web.Request) (interface{}, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *web.Request) interface{}); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *web.Request) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CompleteFormService_GetFormData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFormData'
type CompleteFormService_GetFormData_Call struct {
	*mock.Call
}

// GetFormData is a helper method to define mock.On call
//   - ctx context.Context
//   - req *web.Request
func (_e *CompleteFormService_Expecter) GetFormData(ctx any, req any) *CompleteFormService_GetFormData_Call {
	return &CompleteFormService_GetFormData_Call{Call: _e.mock.On("GetFormData", ctx, req)}
}

func (_c *CompleteFormService_GetFormData_Call) Run(run func(ctx context.Context, req *web.Request)) *CompleteFormService_GetFormData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *web.Request
		if args[1] != nil {
			arg1 = args[1].(*web.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CompleteFormService_GetFormData_Call) Return(ifaceVal interface{}, err error) *CompleteFormService_GetFormData_Call {
	_c.Call.Return(ifaceVal, err)
	return _c
}

func (_c *CompleteFormService_GetFormData_Call) RunAndReturn(run func(ctx context.Context, req *web.Request) (interface{}, error)) *CompleteFormService_GetFormData_Call {
	_c.Call.Return(run)
	return _c
}

// Validate provides a mock function for the type CompleteFormService
func (_mock *CompleteFormService) Validate(ctx context.Context, req *web.Request, validatorProvider domain.ValidatorProvider, formData interface{}) (*domain.ValidationInfo, error) {
	ret := _mock.Called(ctx, req, validatorProvider, formData)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 *domain.ValidationInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *web.Request, domain.ValidatorProvider, interface{}) (*domain.ValidationInfo, error)); ok {
		return returnFunc(ctx, req, validatorProvider, formData)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *web.Request, domain.ValidatorProvider, interface{}) *domain.ValidationInfo); ok {
		r0 = returnFunc(ctx, req, validatorProvider, formData)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ValidationInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *web.Request, domain.ValidatorProvider, interface{}) error); ok {
		r1 = returnFunc(ctx, req, validatorProvider, formData)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CompleteFormService_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type CompleteFormService_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - ctx context.Context
//   - req *web.Request
//   - validatorProvider domain.ValidatorProvider
//   - formData interface{}
func (_e *CompleteFormService_Expecter) Validate(ctx any, req any, validatorProvider any, formData any) *CompleteFormService_Validate_Call {
	return &CompleteFormService_Validate_Call{Call: _e.mock.On("Validate", ctx, req, validatorProvider, formData)}
}

func (_c *CompleteFormService_Validate_Call) Run(run func(ctx context.Context, req *web.Request, validatorProvider domain.ValidatorProvider, formData interface{})) *CompleteFormService_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *web.Request
		if args[1] != nil {
			arg1 = args[1].(*web.Request)
		}
		var arg2 domain.ValidatorProvider
		if args[2] != nil {
			arg2 = args[2].(domain.ValidatorProvider)
		}
		var arg3 interface{}
		if args[3] != nil {
			arg3 = args[3].(interface{})
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *CompleteFormService_Validate_Call) Return(validationInfo *domain.ValidationInfo, err error) *CompleteFormService_Validate_Call {
	_c.Call.Return(validationInfo, err)
	return _c
}

func (_c *CompleteFormService_Validate_Call) RunAndReturn(run func(ctx context.Context, req *web.Request, validatorProvider domain.ValidatorProvider, formData interface{}) (*domain.ValidationInfo, error)) *CompleteFormService_Validate_Call {
	_c.Call.Return(run)
	return _c
}
