// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"flamingo.me/flamingo/v3/framework/web"
	mock "github.com/stretchr/testify/mock"
)

// NewDefaultFormDataProvider creates a new instance of DefaultFormDataProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDefaultFormDataProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *DefaultFormDataProvider {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &DefaultFormDataProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// DefaultFormDataProvider is an autogenerated mock type for the DefaultFormDataProvider type
type DefaultFormDataProvider struct {
	mock.Mock
}

type DefaultFormDataProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *DefaultFormDataProvider) EXPECT() *DefaultFormDataProvider_Expecter {
	return &DefaultFormDataProvider_Expecter{mock: &_m.Mock}
}

// GetFormData provides a mock function for the type DefaultFormDataProvider
func (_mock *DefaultFormDataProvider) GetFormData(ctx context.Context, req *web.Request) (interface{}, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetFormData")
	}

	var r0 interface{}
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *web.Request) (interface{}, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *web.Request) interface{}); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *web.Request) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DefaultFormDataProvider_GetFormData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFormData'
type DefaultFormDataProvider_GetFormData_Call struct {
	*mock.Call
}

// GetFormData is a helper method to define mock.On call
//   - ctx context.Context
//   - req *web.Request
func (_e *DefaultFormDataProvider_Expecter) GetFormData(ctx any, req any) *DefaultFormDataProvider_GetFormData_Call {
	return &DefaultFormDataProvider_GetFormData_Call{Call: _e.mock.On("GetFormData", ctx, req)}
}

func (_c *DefaultFormDataProvider_GetFormData_Call) Run(run func(ctx context.Context, req *web.Request)) *DefaultFormDataProvider_GetFormData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *web.Request
		if args[1] != nil {
			arg1 = args[1].(*web.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DefaultFormDataProvider_GetFormData_Call) Return(ifaceVal interface{}, err error) *DefaultFormDataProvider_GetFormData_Call {
	_c.Call.Return(ifaceVal, err)
	return _c
}

func (_c *DefaultFormDataProvider_GetFormData_Call) RunAndReturn(run func(ctx context.Context, req *web.Request) (interface{}, error)) *DefaultFormDataProvider_GetFormData_Call {
	_c.Call.Return(run)
	return _c
}
