// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"net/url"

	"flamingo.me/flamingo/v3/framework/web"
	mock "github.com/stretchr/testify/mock"
)

// NewDefaultFormDataDecoder creates a new instance of DefaultFormDataDecoder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDefaultFormDataDecoder(t interface {
	mock.TestingT
	Cleanup(func())
}) *DefaultFormDataDecoder {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &DefaultFormDataDecoder{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// DefaultFormDataDecoder is an autogenerated mock type for the DefaultFormDataDecoder type
type DefaultFormDataDecoder struct {
	mock.Mock
}

type DefaultFormDataDecoder_Expecter struct {
	mock *mock.Mock
}

func (_m *DefaultFormDataDecoder) EXPECT() *DefaultFormDataDecoder_Expecter {
	return &DefaultFormDataDecoder_Expecter{mock: &_m.Mock}
}

// Decode provides a mock function for the type DefaultFormDataDecoder
func (_mock *DefaultFormDataDecoder) Decode(ctx context.Context, req *web.Request, values url.Values, formData interface{}) (interface{}, error) {
	ret := _mock.Called(ctx, req, values, formData)

	if len(ret) == 0 {
		panic("no return value specified for Decode")
	}

	var r0 interface{}
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *web.Request, url.Values, interface{}) (interface{}, error)); ok {
		return returnFunc(ctx, req, values, formData)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *web.Request, url.Values, interface{}) interface{}); ok {
		r0 = returnFunc(ctx, req, values, formData)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *web.Request, url.Values, interface{}) error); ok {
		r1 = returnFunc(ctx, req, values, formData)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DefaultFormDataDecoder_Decode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decode'
type DefaultFormDataDecoder_Decode_Call struct {
	*mock.Call
}

// Decode is a helper method to define mock.On call
//   - ctx context.Context
//   - req *web.Request
//   - values url.Values
//   - formData interface{}
func (_e *DefaultFormDataDecoder_Expecter) Decode(ctx any, req any, values any, formData any) *DefaultFormDataDecoder_Decode_Call {
	return &DefaultFormDataDecoder_Decode_Call{Call: _e.mock.On("Decode", ctx, req, values, formData)}
}

func (_c *DefaultFormDataDecoder_Decode_Call) Run(run func(ctx context.Context, req *web.Request, values url.Values, formData interface{})) *DefaultFormDataDecoder_Decode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *web.Request
		if args[1] != nil {
			arg1 = args[1].(*web.Request)
		}
		var arg2 url.Values
		if args[2] != nil {
			arg2 = args[2].(url.Values)
		}
		var arg3 interface{}
		if args[3] != nil {
			arg3 = args[3].(interface{})
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *DefaultFormDataDecoder_Decode_Call) Return(ifaceVal interface{}, err error) *DefaultFormDataDecoder_Decode_Call {
	_c.Call.Return(ifaceVal, err)
	return _c
}

func (_c *DefaultFormDataDecoder_Decode_Call) RunAndReturn(run func(ctx context.Context, req *web.Request, values url.Values, formData interface{}) (interface{}, error)) *DefaultFormDataDecoder_Decode_Call {
	_c.Call.Return(run)
	return _c
}
