// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/go-playground/validator/v10"
	mock "github.com/stretchr/testify/mock"
)

// NewFieldValidator creates a new instance of FieldValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFieldValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *FieldValidator {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &FieldValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// FieldValidator is an autogenerated mock type for the FieldValidator type
type FieldValidator struct {
	mock.Mock
}

type FieldValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *FieldValidator) EXPECT() *FieldValidator_Expecter {
	return &FieldValidator_Expecter{mock: &_m.Mock}
}

// ValidateField provides a mock function for the type FieldValidator
func (_mock *FieldValidator) ValidateField(ctx context.Context, fl validator.FieldLevel) bool {
	ret := _mock.Called(ctx, fl)

	if len(ret) == 0 {
		panic("no return value specified for ValidateField")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(context.Context, validator.FieldLevel) bool); ok {
		r0 = returnFunc(ctx, fl)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// FieldValidator_ValidateField_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateField'
type FieldValidator_ValidateField_Call struct {
	*mock.Call
}

// ValidateField is a helper method to define mock.On call
//   - ctx context.Context
//   - fl validator.FieldLevel
func (_e *FieldValidator_Expecter) ValidateField(ctx any, fl any) *FieldValidator_ValidateField_Call {
	return &FieldValidator_ValidateField_Call{Call: _e.mock.On("ValidateField", ctx, fl)}
}

func (_c *FieldValidator_ValidateField_Call) Run(run func(ctx context.Context, fl validator.FieldLevel)) *FieldValidator_ValidateField_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 validator.FieldLevel
		if args[1] != nil {
			arg1 = args[1].(validator.FieldLevel)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *FieldValidator_ValidateField_Call) Return(b bool) *FieldValidator_ValidateField_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *FieldValidator_ValidateField_Call) RunAndReturn(run func(ctx context.Context, fl validator.FieldLevel) bool) *FieldValidator_ValidateField_Call {
	_c.Call.Return(run)
	return _c
}

// ValidatorName provides a mock function for the type FieldValidator
func (_mock *FieldValidator) ValidatorName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ValidatorName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// FieldValidator_ValidatorName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidatorName'
type FieldValidator_ValidatorName_Call struct {
	*mock.Call
}

// ValidatorName is a helper method to define mock.On call
func (_e *FieldValidator_Expecter) ValidatorName() *FieldValidator_ValidatorName_Call {
	return &FieldValidator_ValidatorName_Call{Call: _e.mock.On("ValidatorName")}
}

func (_c *FieldValidator_ValidatorName_Call) Run(run func()) *FieldValidator_ValidatorName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *FieldValidator_ValidatorName_Call) Return(s string) *FieldValidator_ValidatorName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *FieldValidator_ValidatorName_Call) RunAndReturn(run func() string) *FieldValidator_ValidatorName_Call {
	_c.Call.Return(run)
	return _c
}
