// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"net/url"

	mock "github.com/stretchr/testify/mock"
)

// NewFormDataEncoder creates a new instance of FormDataEncoder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFormDataEncoder(t interface {
	mock.TestingT
	Cleanup(func())
}) *FormDataEncoder {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &FormDataEncoder{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// FormDataEncoder is an autogenerated mock type for the FormDataEncoder type
type FormDataEncoder struct {
	mock.Mock
}

type FormDataEncoder_Expecter struct {
	mock *mock.Mock
}

func (_m *FormDataEncoder) EXPECT() *FormDataEncoder_Expecter {
	return &FormDataEncoder_Expecter{mock: &_m.Mock}
}

// Encode provides a mock function for the type FormDataEncoder
func (_mock *FormDataEncoder) Encode(ctx context.Context, formData interface{}) (url.Values, error) {
	ret := _mock.Called(ctx, formData)

	if len(ret) == 0 {
		panic("no return value specified for Encode")
	}

	var r0 url.Values
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, interface{}) (url.Values, error)); ok {
		return returnFunc(ctx, formData)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, interface{}) url.Values); ok {
		r0 = returnFunc(ctx, formData)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(url.Values)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, interface{}) error); ok {
		r1 = returnFunc(ctx, formData)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// FormDataEncoder_Encode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Encode'
type FormDataEncoder_Encode_Call struct {
	*mock.Call
}

// Encode is a helper method to define mock.On call
//   - ctx context.Context
//   - formData interface{}
func (_e *FormDataEncoder_Expecter) Encode(ctx any, formData any) *FormDataEncoder_Encode_Call {
	return &FormDataEncoder_Encode_Call{Call: _e.mock.On("Encode", ctx, formData)}
}

func (_c *FormDataEncoder_Encode_Call) Run(run func(ctx context.Context, formData interface{})) *FormDataEncoder_Encode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *FormDataEncoder_Encode_Call) Return(values url.Values, err error) *FormDataEncoder_Encode_Call {
	_c.Call.Return(values, err)
	return _c
}

func (_c *FormDataEncoder_Encode_Call) RunAndReturn(run func(ctx context.Context, formData interface{}) (url.Values, error)) *FormDataEncoder_Encode_Call {
	_c.Call.Return(run)
	return _c
}
