// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"flamingo.me/flamingo/v3/framework/web"
	"flamingo.me/form/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewFormHandler creates a new instance of FormHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFormHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *FormHandler {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &FormHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// FormHandler is an autogenerated mock type for the FormHandler type
type FormHandler struct {
	mock.Mock
}

type FormHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *FormHandler) EXPECT() *FormHandler_Expecter {
	return &FormHandler_Expecter{mock: &_m.Mock}
}

// HandleForm provides a mock function for the type FormHandler
func (_mock *FormHandler) HandleForm(ctx context.Context, req *web.Request) (*domain.Form, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for HandleForm")
	}

	var r0 *domain.Form
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *web.Request) (*domain.Form, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *web.Request) *domain.Form); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Form)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *web.Request) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// FormHandler_HandleForm_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleForm'
type FormHandler_HandleForm_Call struct {
	*mock.Call
}

// HandleForm is a helper method to define mock.On call
//   - ctx context.Context
//   - req *web.Request
func (_e *FormHandler_Expecter) HandleForm(ctx any, req any) *FormHandler_HandleForm_Call {
	return &FormHandler_HandleForm_Call{Call: _e.mock.On("HandleForm", ctx, req)}
}

func (_c *FormHandler_HandleForm_Call) Run(run func(ctx context.Context, req *web.Request)) *FormHandler_HandleForm_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *web.Request
		if args[1] != nil {
			arg1 = args[1].(*web.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *FormHandler_HandleForm_Call) Return(form *domain.Form, err error) *FormHandler_HandleForm_Call {
	_c.Call.Return(form, err)
	return _c
}

func (_c *FormHandler_HandleForm_Call) RunAndReturn(run func(ctx context.Context, req *web.Request) (*domain.Form, error)) *FormHandler_HandleForm_Call {
	_c.Call.Return(run)
	return _c
}

// HandleSubmittedForm provides a mock function for the type FormHandler
func (_mock *FormHandler) HandleSubmittedForm(ctx context.Context, req *web.Request) (*domain.Form, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for HandleSubmittedForm")
	}

	var r0 *domain.Form
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *web.Request) (*domain.Form, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *web.Request) *domain.Form); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Form)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *web.Request) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// FormHandler_HandleSubmittedForm_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleSubmittedForm'
type FormHandler_HandleSubmittedForm_Call struct {
	*mock.Call
}

// HandleSubmittedForm is a helper method to define mock.On call
//   - ctx context.Context
//   - req *web.Request
func (_e *FormHandler_Expecter) HandleSubmittedForm(ctx any, req any) *FormHandler_HandleSubmittedForm_Call {
	return &FormHandler_HandleSubmittedForm_Call{Call: _e.mock.On("HandleSubmittedForm", ctx, req)}
}

func (_c *FormHandler_HandleSubmittedForm_Call) Run(run func(ctx context.Context, req *web.Request)) *FormHandler_HandleSubmittedForm_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *web.Request
		if args[1] != nil {
			arg1 = args[1].(*web.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *FormHandler_HandleSubmittedForm_Call) Return(form *domain.Form, err error) *FormHandler_HandleSubmittedForm_Call {
	_c.Call.Return(form, err)
	return _c
}

func (_c *FormHandler_HandleSubmittedForm_Call) RunAndReturn(run func(ctx context.Context, req *web.Request) (*domain.Form, error)) *FormHandler_HandleSubmittedForm_Call {
	_c.Call.Return(run)
	return _c
}

// HandleSubmittedGETForm provides a mock function for the type FormHandler
func (_mock *FormHandler) HandleSubmittedGETForm(ctx context.Context, req *web.Request) (*domain.Form, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for HandleSubmittedGETForm")
	}

	var r0 *domain.Form
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *web.Request) (*domain.Form, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *web.Request) *domain.Form); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Form)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *web.Request) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// FormHandler_HandleSubmittedGETForm_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleSubmittedGETForm'
type FormHandler_HandleSubmittedGETForm_Call struct {
	*mock.Call
}

// HandleSubmittedGETForm is a helper method to define mock.On call
//   - ctx context.Context
//   - req *web.Request
func (_e *FormHandler_Expecter) HandleSubmittedGETForm(ctx any, req any) *FormHandler_HandleSubmittedGETForm_Call {
	return &FormHandler_HandleSubmittedGETForm_Call{Call: _e.mock.On("HandleSubmittedGETForm", ctx, req)}
}

func (_c *FormHandler_HandleSubmittedGETForm_Call) Run(run func(ctx context.Context, req *web.Request)) *FormHandler_HandleSubmittedGETForm_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *web.Request
		if args[1] != nil {
			arg1 = args[1].(*web.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *FormHandler_HandleSubmittedGETForm_Call) Return(form *domain.Form, err error) *FormHandler_HandleSubmittedGETForm_Call {
	_c.Call.Return(form, err)
	return _c
}

func (_c *FormHandler_HandleSubmittedGETForm_Call) RunAndReturn(run func(ctx context.Context, req *web.Request) (*domain.Form, error)) *FormHandler_HandleSubmittedGETForm_Call {
	_c.Call.Return(run)
	return _c
}

// HandleUnsubmittedForm provides a mock function for the type FormHandler
func (_mock *FormHandler) HandleUnsubmittedForm(ctx context.Context, req *web.Request) (*domain.Form, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for HandleUnsubmittedForm")
	}

	var r0 *domain.Form
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *web.Request) (*domain.Form, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *web.Request) *domain.Form); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Form)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *web.Request) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// FormHandler_HandleUnsubmittedForm_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleUnsubmittedForm'
type FormHandler_HandleUnsubmittedForm_Call struct {
	*mock.Call
}

// HandleUnsubmittedForm is a helper method to define mock.On call
//   - ctx context.Context
//   - req *web.Request
func (_e *FormHandler_Expecter) HandleUnsubmittedForm(ctx any, req any) *FormHandler_HandleUnsubmittedForm_Call {
	return &FormHandler_HandleUnsubmittedForm_Call{Call: _e.mock.On("HandleUnsubmittedForm", ctx, req)}
}

func (_c *FormHandler_HandleUnsubmittedForm_Call) Run(run func(ctx context.Context, req *web.Request)) *FormHandler_HandleUnsubmittedForm_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *web.Request
		if args[1] != nil {
			arg1 = args[1].(*web.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *FormHandler_HandleUnsubmittedForm_Call) Return(form *domain.Form, err error) *FormHandler_HandleUnsubmittedForm_Call {
	_c.Call.Return(form, err)
	return _c
}

func (_c *FormHandler_HandleUnsubmittedForm_Call) RunAndReturn(run func(ctx context.Context, req *web.Request) (*domain.Form, error)) *FormHandler_HandleUnsubmittedForm_Call {
	_c.Call.Return(run)
	return _c
}
