// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// FormExtension is an autogenerated mock type for the FormExtension type
type FormExtension struct {
	mock.Mock
}

type FormExtension_Expecter struct {
	mock *mock.Mock
}

func (_m *FormExtension) EXPECT() *FormExtension_Expecter {
	return &FormExtension_Expecter{mock: &_m.Mock}
}

// NewFormExtension creates a new instance of FormExtension. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFormExtension(t interface {
	mock.TestingT
	Cleanup(func())
}) *FormExtension {
	mock := &FormExtension{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
