// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"flamingo.me/flamingo/v3/framework/web"
	"flamingo.me/form/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewFormDataValidator creates a new instance of FormDataValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFormDataValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *FormDataValidator {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &FormDataValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// FormDataValidator is an autogenerated mock type for the FormDataValidator type
type FormDataValidator struct {
	mock.Mock
}

type FormDataValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *FormDataValidator) EXPECT() *FormDataValidator_Expecter {
	return &FormDataValidator_Expecter{mock: &_m.Mock}
}

// Validate provides a mock function for the type FormDataValidator
func (_mock *FormDataValidator) Validate(ctx context.Context, req *web.Request, validatorProvider domain.ValidatorProvider, formData interface{}) (*domain.ValidationInfo, error) {
	ret := _mock.Called(ctx, req, validatorProvider, formData)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 *domain.ValidationInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *web.Request, domain.ValidatorProvider, interface{}) (*domain.ValidationInfo, error)); ok {
		return returnFunc(ctx, req, validatorProvider, formData)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *web.Request, domain.ValidatorProvider, interface{}) *domain.ValidationInfo); ok {
		r0 = returnFunc(ctx, req, validatorProvider, formData)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ValidationInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *web.Request, domain.ValidatorProvider, interface{}) error); ok {
		r1 = returnFunc(ctx, req, validatorProvider, formData)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// FormDataValidator_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type FormDataValidator_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - ctx context.Context
//   - req *web.Request
//   - validatorProvider domain.ValidatorProvider
//   - formData interface{}
func (_e *FormDataValidator_Expecter) Validate(ctx any, req any, validatorProvider any, formData any) *FormDataValidator_Validate_Call {
	return &FormDataValidator_Validate_Call{Call: _e.mock.On("Validate", ctx, req, validatorProvider, formData)}
}

func (_c *FormDataValidator_Validate_Call) Run(run func(ctx context.Context, req *web.Request, validatorProvider domain.ValidatorProvider, formData interface{})) *FormDataValidator_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *web.Request
		if args[1] != nil {
			arg1 = args[1].(*web.Request)
		}
		var arg2 domain.ValidatorProvider
		if args[2] != nil {
			arg2 = args[2].(domain.ValidatorProvider)
		}
		var arg3 interface{}
		if args[3] != nil {
			arg3 = args[3].(interface{})
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *FormDataValidator_Validate_Call) Return(validationInfo *domain.ValidationInfo, err error) *FormDataValidator_Validate_Call {
	_c.Call.Return(validationInfo, err)
	return _c
}

func (_c *FormDataValidator_Validate_Call) RunAndReturn(run func(ctx context.Context, req *web.Request, validatorProvider domain.ValidatorProvider, formData interface{}) (*domain.ValidationInfo, error)) *FormDataValidator_Validate_Call {
	_c.Call.Return(run)
	return _c
}
