// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewFormExtension creates a new instance of FormExtension. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFormExtension(t interface {
	mock.TestingT
	Cleanup(func())
}) *FormExtension {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &FormExtension{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// FormExtension is an autogenerated mock type for the FormExtension type
type FormExtension struct {
	mock.Mock
}

type FormExtension_Expecter struct {
	mock *mock.Mock
}

func (_m *FormExtension) EXPECT() *FormExtension_Expecter {
	return &FormExtension_Expecter{mock: &_m.Mock}
}
