// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"reflect"

	"github.com/go-playground/validator/v10"
	mock "github.com/stretchr/testify/mock"
)

// NewStructLevel creates a new instance of StructLevel. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStructLevel(t interface {
	mock.TestingT
	Cleanup(func())
}) *StructLevel {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &StructLevel{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// StructLevel is an autogenerated mock type for the StructLevel type
type StructLevel struct {
	mock.Mock
}

type StructLevel_Expecter struct {
	mock *mock.Mock
}

func (_m *StructLevel) EXPECT() *StructLevel_Expecter {
	return &StructLevel_Expecter{mock: &_m.Mock}
}

// Current provides a mock function for the type StructLevel
func (_mock *StructLevel) Current() reflect.Value {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Current")
	}

	var r0 reflect.Value
	if returnFunc, ok := ret.Get(0).(func() reflect.Value); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(reflect.Value)
	}
	return r0
}

// StructLevel_Current_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Current'
type StructLevel_Current_Call struct {
	*mock.Call
}

// Current is a helper method to define mock.On call
func (_e *StructLevel_Expecter) Current() *StructLevel_Current_Call {
	return &StructLevel_Current_Call{Call: _e.mock.On("Current")}
}

func (_c *StructLevel_Current_Call) Run(run func()) *StructLevel_Current_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *StructLevel_Current_Call) Return(value reflect.Value) *StructLevel_Current_Call {
	_c.Call.Return(value)
	return _c
}

func (_c *StructLevel_Current_Call) RunAndReturn(run func() reflect.Value) *StructLevel_Current_Call {
	_c.Call.Return(run)
	return _c
}

// ExtractType provides a mock function for the type StructLevel
func (_mock *StructLevel) ExtractType(field reflect.Value) (reflect.Value, reflect.Kind, bool) {
	ret := _mock.Called(field)

	if len(ret) == 0 {
		panic("no return value specified for ExtractType")
	}

	var r0 reflect.Value
	var r1 reflect.Kind
	var r2 bool
	if returnFunc, ok := ret.Get(0).(func(reflect.Value) (reflect.Value, reflect.Kind, bool)); ok {
		return returnFunc(field)
	}
	if returnFunc, ok := ret.Get(0).(func(reflect.Value) reflect.Value); ok {
		r0 = returnFunc(field)
	} else {
		r0 = ret.Get(0).(reflect.Value)
	}
	if returnFunc, ok := ret.Get(1).(func(reflect.Value) reflect.Kind); ok {
		r1 = returnFunc(field)
	} else {
		r1 = ret.Get(1).(reflect.Kind)
	}
	if returnFunc, ok := ret.Get(2).(func(reflect.Value) bool); ok {
		r2 = returnFunc(field)
	} else {
		r2 = ret.Get(2).(bool)
	}
	return r0, r1, r2
}

// StructLevel_ExtractType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExtractType'
type StructLevel_ExtractType_Call struct {
	*mock.Call
}

// ExtractType is a helper method to define mock.On call
//   - field reflect.Value
func (_e *StructLevel_Expecter) ExtractType(field any) *StructLevel_ExtractType_Call {
	return &StructLevel_ExtractType_Call{Call: _e.mock.On("ExtractType", field)}
}

func (_c *StructLevel_ExtractType_Call) Run(run func(field reflect.Value)) *StructLevel_ExtractType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 reflect.Value
		if args[0] != nil {
			arg0 = args[0].(reflect.Value)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *StructLevel_ExtractType_Call) Return(value reflect.Value, kind reflect.Kind, nullable bool) *StructLevel_ExtractType_Call {
	_c.Call.Return(value, kind, nullable)
	return _c
}

func (_c *StructLevel_ExtractType_Call) RunAndReturn(run func(field reflect.Value) (reflect.Value, reflect.Kind, bool)) *StructLevel_ExtractType_Call {
	_c.Call.Return(run)
	return _c
}

// Parent provides a mock function for the type StructLevel
func (_mock *StructLevel) Parent() reflect.Value {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Parent")
	}

	var r0 reflect.Value
	if returnFunc, ok := ret.Get(0).(func() reflect.Value); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(reflect.Value)
	}
	return r0
}

// StructLevel_Parent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Parent'
type StructLevel_Parent_Call struct {
	*mock.Call
}

// Parent is a helper method to define mock.On call
func (_e *StructLevel_Expecter) Parent() *StructLevel_Parent_Call {
	return &StructLevel_Parent_Call{Call: _e.mock.On("Parent")}
}

func (_c *StructLevel_Parent_Call) Run(run func()) *StructLevel_Parent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *StructLevel_Parent_Call) Return(value reflect.Value) *StructLevel_Parent_Call {
	_c.Call.Return(value)
	return _c
}

func (_c *StructLevel_Parent_Call) RunAndReturn(run func() reflect.Value) *StructLevel_Parent_Call {
	_c.Call.Return(run)
	return _c
}

// ReportError provides a mock function for the type StructLevel
func (_mock *StructLevel) ReportError(field interface{}, fieldName string, structFieldName string, tag string, param string) {
	_mock.Called(field, fieldName, structFieldName, tag, param)
	return
}

// StructLevel_ReportError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReportError'
type StructLevel_ReportError_Call struct {
	*mock.Call
}

// ReportError is a helper method to define mock.On call
//   - field interface{}
//   - fieldName string
//   - structFieldName string
//   - tag string
//   - param string
func (_e *StructLevel_Expecter) ReportError(field any, fieldName any, structFieldName any, tag any, param any) *StructLevel_ReportError_Call {
	return &StructLevel_ReportError_Call{Call: _e.mock.On("ReportError", field, fieldName, structFieldName, tag, param)}
}

func (_c *StructLevel_ReportError_Call) Run(run func(field interface{}, fieldName string, structFieldName string, tag string, param string)) *StructLevel_ReportError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *StructLevel_ReportError_Call) Return() *StructLevel_ReportError_Call {
	_c.Call.Return()
	return _c
}

func (_c *StructLevel_ReportError_Call) RunAndReturn(run func(field interface{}, fieldName string, structFieldName string, tag string, param string)) *StructLevel_ReportError_Call {
	_c.Run(run)
	return _c
}

// ReportValidationErrors provides a mock function for the type StructLevel
func (_mock *StructLevel) ReportValidationErrors(relativeNamespace string, relativeActualNamespace string, errs validator.ValidationErrors) {
	_mock.Called(relativeNamespace, relativeActualNamespace, errs)
	return
}

// StructLevel_ReportValidationErrors_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReportValidationErrors'
type StructLevel_ReportValidationErrors_Call struct {
	*mock.Call
}

// ReportValidationErrors is a helper method to define mock.On call
//   - relativeNamespace string
//   - relativeActualNamespace string
//   - errs validator.ValidationErrors
func (_e *StructLevel_Expecter) ReportValidationErrors(relativeNamespace any, relativeActualNamespace any, errs any) *StructLevel_ReportValidationErrors_Call {
	return &StructLevel_ReportValidationErrors_Call{Call: _e.mock.On("ReportValidationErrors", relativeNamespace, relativeActualNamespace, errs)}
}

func (_c *StructLevel_ReportValidationErrors_Call) Run(run func(relativeNamespace string, relativeActualNamespace string, errs validator.ValidationErrors)) *StructLevel_ReportValidationErrors_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 validator.ValidationErrors
		if args[2] != nil {
			arg2 = args[2].(validator.ValidationErrors)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *StructLevel_ReportValidationErrors_Call) Return() *StructLevel_ReportValidationErrors_Call {
	_c.Call.Return()
	return _c
}

func (_c *StructLevel_ReportValidationErrors_Call) RunAndReturn(run func(relativeNamespace string, relativeActualNamespace string, errs validator.ValidationErrors)) *StructLevel_ReportValidationErrors_Call {
	_c.Run(run)
	return _c
}

// Top provides a mock function for the type StructLevel
func (_mock *StructLevel) Top() reflect.Value {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Top")
	}

	var r0 reflect.Value
	if returnFunc, ok := ret.Get(0).(func() reflect.Value); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(reflect.Value)
	}
	return r0
}

// StructLevel_Top_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Top'
type StructLevel_Top_Call struct {
	*mock.Call
}

// Top is a helper method to define mock.On call
func (_e *StructLevel_Expecter) Top() *StructLevel_Top_Call {
	return &StructLevel_Top_Call{Call: _e.mock.On("Top")}
}

func (_c *StructLevel_Top_Call) Run(run func()) *StructLevel_Top_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *StructLevel_Top_Call) Return(value reflect.Value) *StructLevel_Top_Call {
	_c.Call.Return(value)
	return _c
}

func (_c *StructLevel_Top_Call) RunAndReturn(run func() reflect.Value) *StructLevel_Top_Call {
	_c.Call.Return(run)
	return _c
}

// Validator provides a mock function for the type StructLevel
func (_mock *StructLevel) Validator() *validator.Validate {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Validator")
	}

	var r0 *validator.Validate
	if returnFunc, ok := ret.Get(0).(func() *validator.Validate); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*validator.Validate)
		}
	}
	return r0
}

// StructLevel_Validator_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validator'
type StructLevel_Validator_Call struct {
	*mock.Call
}

// Validator is a helper method to define mock.On call
func (_e *StructLevel_Expecter) Validator() *StructLevel_Validator_Call {
	return &StructLevel_Validator_Call{Call: _e.mock.On("Validator")}
}

func (_c *StructLevel_Validator_Call) Run(run func()) *StructLevel_Validator_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *StructLevel_Validator_Call) Return(validate *validator.Validate) *StructLevel_Validator_Call {
	_c.Call.Return(validate)
	return _c
}

func (_c *StructLevel_Validator_Call) RunAndReturn(run func() *validator.Validate) *StructLevel_Validator_Call {
	_c.Call.Return(run)
	return _c
}
