// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/go-playground/validator/v10"
	mock "github.com/stretchr/testify/mock"
)

// NewStructValidator creates a new instance of StructValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStructValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *StructValidator {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &StructValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// StructValidator is an autogenerated mock type for the StructValidator type
type StructValidator struct {
	mock.Mock
}

type StructValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *StructValidator) EXPECT() *StructValidator_Expecter {
	return &StructValidator_Expecter{mock: &_m.Mock}
}

// StructType provides a mock function for the type StructValidator
func (_mock *StructValidator) StructType() interface{} {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for StructType")
	}

	var r0 interface{}
	if returnFunc, ok := ret.Get(0).(func() interface{}); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}
	return r0
}

// StructValidator_StructType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StructType'
type StructValidator_StructType_Call struct {
	*mock.Call
}

// StructType is a helper method to define mock.On call
func (_e *StructValidator_Expecter) StructType() *StructValidator_StructType_Call {
	return &StructValidator_StructType_Call{Call: _e.mock.On("StructType")}
}

func (_c *StructValidator_StructType_Call) Run(run func()) *StructValidator_StructType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *StructValidator_StructType_Call) Return(ifaceVal interface{}) *StructValidator_StructType_Call {
	_c.Call.Return(ifaceVal)
	return _c
}

func (_c *StructValidator_StructType_Call) RunAndReturn(run func() interface{}) *StructValidator_StructType_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateStruct provides a mock function for the type StructValidator
func (_mock *StructValidator) ValidateStruct(ctx context.Context, sl validator.StructLevel) {
	_mock.Called(ctx, sl)
	return
}

// StructValidator_ValidateStruct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateStruct'
type StructValidator_ValidateStruct_Call struct {
	*mock.Call
}

// ValidateStruct is a helper method to define mock.On call
//   - ctx context.Context
//   - sl validator.StructLevel
func (_e *StructValidator_Expecter) ValidateStruct(ctx any, sl any) *StructValidator_ValidateStruct_Call {
	return &StructValidator_ValidateStruct_Call{Call: _e.mock.On("ValidateStruct", ctx, sl)}
}

func (_c *StructValidator_ValidateStruct_Call) Run(run func(ctx context.Context, sl validator.StructLevel)) *StructValidator_ValidateStruct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 validator.StructLevel
		if args[1] != nil {
			arg1 = args[1].(validator.StructLevel)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StructValidator_ValidateStruct_Call) Return() *StructValidator_ValidateStruct_Call {
	_c.Call.Return()
	return _c
}

func (_c *StructValidator_ValidateStruct_Call) RunAndReturn(run func(ctx context.Context, sl validator.StructLevel)) *StructValidator_ValidateStruct_Call {
	_c.Run(run)
	return _c
}
